
services:
  backend_rds:
    build:
      context: ./backend_rds
    ports:
      - "8001:8001"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  backend_redis:
    build:
      context: ./backend_redis
    ports:
      - "8002:8002"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=0

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_RDS_URL=${BACKEND_RDS_URL}
      - BACKEND_REDIS_URL=${BACKEND_REDIS_URL}
    depends_on:
      - backend_rds
      - backend_redis
