name: Deploy Docker Images to ECR
on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log-in to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build and Push frontend Image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/frontend:$IMAGE_TAG -f frontend/Dockerfile .
          docker push $ECR_REGISTRY/frontend:$IMAGE_TAG

      - name: Build and Push backend_rds Image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/backend_rds:$IMAGE_TAG -f backend_rds/Dockerfile .
          docker push $ECR_REGISTRY/backend_rds:$IMAGE_TAG

      - name: Build and Push backend_redis Image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/backend_redis:$IMAGE_TAG -f backend_redis/Dockerfile .
          docker push $ECR_REGISTRY/backend_redis:$IMAGE_TAG